template: true   # required for local templates
valuesFilePath: ./values.yml

resources:
  - name: dbp_repo_1
    type: GitRepo
    configuration:
      gitProvider: {{ .Values.var.gitProvider }}
      path: {{ .Values.var.path }}
      branches:
        include: {{ .Values.var.branches }} 

  - name: dbp_image_1
    type: Image
    configuration:
      registry: {{ .Values.var.artifactory }}
      sourceRepository: {{ .Values.var.repo }}               # <-- required if registry is Artifactory
      imageName: {{ .Values.var.imageName }}
      imageTag: latest
      autoPull: true
      
  - name: dbp_build_info_1
    type: BuildInfo
    configuration:
      sourceArtifactory: {{ .Values.var.artifactory }}
      buildName: dbp_build
      buildNumber: 1    

  #- name: dbp_promoted_build_info
  #  type: BuildInfo
  #  configuration:
  #    sourceArtifactory: {{ .Values.var.artifactory }}
  #    buildName: dbp_build
  #    buildNumber: 1
      

pipelines:
  - name: {{ .Values.var.pipelineName }}
    configuration:
      nodePool: {{ .Values.var.nodePool }}
    steps:

      - name: docker_file_base_image_update
        type: Bash
        configuration:
          affinityGroup: dbp_group
          inputResources:
            - name: service_a_build_info
        execution:
          onExecute:
            - echo $service_a_build_info
            - var=$service_a_build_info
            - sed -i "1s/.*/$var/" Dockerfile1

      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: {{ .Values.var.imageName }}   # replace with your image path and name
          dockerImageTag: ${run_number}
          inputSteps:
            - name: docker_file_base_image_update
          inputResources:
            - name: dbp_repo_1
          integrations:
            - name: {{ .Values.var.artifactory }}                             # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: {{ .Values.var.repo }}
          integrations:
            - name: {{ .Values.var.artifactory }}                             # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info_1
      #- name: promote_dbp_build
      #  type: PromoteBuild
      #  configuration:
      #    targetRepository: demo-pipelines
      #    integrations:
      #      - name: {{ .Values.serviceA.artifactory }}
      #    inputResources:
      #      - name: dbp_build_info
      #    outputResources:
      #      - name: dbp_promoted_build_info
